name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install dependencies
      run: |
        sudo pip install tox
    - name: Linting
      run: |
        tox -e pep8
    - name: Unit tests
      run: |
        tox -e py3
    - name: Check events
      run: |
        tox -r -e develop run -qq -- archgame_events_check
